language: generic

notifications:
  email: false

before_install:
- |
    mkdir abnf-download &&
    cd ./abnf-download &&
    wget -O abnf.tar.gz https://rschmidmeister.nyc3.digitaloceanspaces.com/binaries/abnf/abnf-x86_64-gnu-linux.tar.gz &&
    tar -xvf abnf.tar.gz &&
    sudo cp ./abnf /usr/local/bin/ &&
    cd ../ &&
    rm -rf ./abnf-download

script:
- make lint
