SPACE = %d32
TAB = %d9
CR = %d13
LF = %d10
CRLF = CR LF

file = *(line)
line = (blank-line / heading / quote / ordered-list / unordered-list / decorator ) line-ending

blank-line = *(whitespace)

heading = heading-prefix text
heading-prefix = "# " / "## " / "### " / "#### "

quote = quote-prefix formatted-text
quote-prefix = "> "

ordered-list = ordered-list-prefix / formatted-text
ordered-list-prefix = ". "

unordered-list = unordered-list-prefix / formatted-text
unordered-list-prefix = "- "

decorator = "[" word "]" whitespace

; temporarily using ascii chars (excluding control chars)
; todo: we need a proper definition for this
text = *(%d32-126)

; todo: define
formatted-text = text

; todo: review + allow all letters not only ascii
word = *(%d48-57 / %d65-90 / %d97-122 / "_")

; todo: decide if CR itself should be allowed as line terminator
line-ending = CRLF / CR / LF

whitespace = TAB / SPACE

file